# Generated by Django 4.2.7 on 2025-09-16 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('driving_hours', models.FloatField()),
                ('on_duty_hours', models.FloatField()),
                ('off_duty_hours', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_hours', models.IntegerField()),
                ('total_distance_miles', models.FloatField()),
                ('total_drive_hours', models.FloatField()),
                ('estimated_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('fuel', 'Fuel'), ('rest', 'Rest'), ('dropoff', 'Dropoff')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('mile_marker', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('status', models.CharField(choices=[('Off Duty', 'Off Duty'), ('Sleeper', 'Sleeper Berth'), ('Driving', 'Driving'), ('On Duty', 'On Duty (Not Driving)'), ('Break', 'Break')], max_length=50)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='routes.dailyschedule')),
            ],
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='routes.trip'),
        ),
    ]
